version: '2'

services:
  gootentests:
    build:
      context: .
    environment:
      - APP_HOST
      - WEB_DRIVER=headless
      - TESTRUN_ID
      - SCOPE
    volumes:
      - '.:/cucumber'
